name: My Custom Action
description: 環境別のシークレットを引き当てるアクション
inputs:
  env_key:
    description: 環境別のキー。STとかPRODとか。
    required: true
  secrets:
    description: シークレット。toJSONして食わせる。
    required: true
outputs:
  TEST1:
    description: 指定された環境のsecret TEST1 (ST_TEST1とかPROD_TEST1とか)
    value: ${{steps.yyy.outputs.TEST1}}

runs:
  using: composite
  steps:
    - id: xxx
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          core.exportVariable('AAAAA', 'aaaaaa');
    - id: yyy
      shell: bash
      env:
        SWITCH_ENV: ${{steps.xxx.outputs.result}}
      run: |
        echo $SWITCH_ENV
        echo "TEST1=$(echo $SWITCH_ENV | jq .TEST1)" >> $GITHUB_OUTPUT
        