on:
  workflow_call:
    outputs:
      b64:
        value: ${{ jobs.testjob.outputs.b64 }}

jobs:
  testjob:
    runs-on: ubuntu-22.04
    outputs:
      b64: ${{steps.xxx.outputs.result}}
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl https://get.volta.sh | bash
          export PATH=$PATH:$HOME/.volta/bin
          volta install node
          volta install pnpm
          pnpm install
      - run: |
          echo ${{github.ref}}
          echo ${{github.base_ref}}
      - id: xxx
        uses: actions/github-script@v7
        with:
          result-encoding: string
          # retries: 3
          script: |
            core.info(JSON.stringify(context.payload.pull_request.base, null, 2));
      - uses: ./.github/actions/my-action2