on:
  workflow_call:
    outputs:
      b64:
        value: ${{ jobs.testjob.outputs.b64 }}
jobs:
  testjob:
    runs-on: ubuntu-22.04
    outputs:
      b64: ${{steps.xxx.outputs.result}}
    steps:
      - run: |
          echo ${{github.ref}}
          echo ${{github.base_ref}}
      - id: xxx
        uses: actions/github-script@v7
        env:
          SECRETS: ${{toJson(secrets)}}
          VARS: ${{toJson(vars)}}
        with:
          result-encoding: string
          # retries: 3
          script: |
            core.info(JSON.stringify(context, null, 2));