on: workflow_call

jobs:
  testjob:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo 'secrets'
          echo $SECRETS > .tmp/secrets.json
          secrets=$(jq to_entries .tmp/secrets.json)
          for item in $secrets; do
            echo $item | rev
            echo '------------------'
          done
          echo ''
          echo $VARS > .tmp/vars.json
          echo 'vars'
          vars=$(jq to_entries .tmp/vars.json)
          for item in $vars; do
            echo $item | rev
            echo '------------------'
          done
        # env:
        #   SECRETS: ${{toJson(secrets)}}
        #   VARS: ${{toJson(vars)}}
