on: workflow_call

jobs:
  testjob:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo 'secrets'
          echo $SECRETS > secrets.json
          secrets=$(jq to_entries secrets.json)
          for item in $secrets; do
            echo $item | rev
            echo '------------------'
          done
          cat secrets.json

          echo ''
          echo 'vars'
          echo $VARS > vars.json
          vars=$(jq to_entries vars.json)
          for item in $vars; do
            echo $item | rev
            echo '------------------'
          done
          cat vars.json
        # env:
        #   SECRETS: ${{toJson(secrets)}}
        #   VARS: ${{toJson(vars)}}
