on: workflow_call

jobs:
  testjob:
    runs-on: ubuntu-22.04
    steps:
      - id: xxx
        uses: actions/github-script@v7
        env:
          SECRETS: ${{toJson(secrets)}}
          VARS: ${{toJson(vars)}}
        
        with:
          result-encoding: string
          retries: 3
          script: |
            const secret = Object.fromEntries(Object.entries(process.env.SECRETS).map(([k, v]) => [k, v.replace(/((.)(?!$))/gm, '$1 ')]));
            core.info(secret);

            const vars = Object.fromEntries(Object.entries(process.env.VARS).map(([k, v]) => [k, v.replace(/((.)(?!$))/gm, '$1 ')]));
            core.info(vars);
          
