on:
  workflow_call:
    
jobs:
  my-job:
    runs-on: ubuntu-22.04
    steps:
      - run:
          echo $EVENT_NAME
          echo $EVENT
        env:
          EVENT: ${{toJson(github.event)}}
          EVENT_NAME: ${{github.event_name}}