on:
  workflow_call:
    outputs:
      b64:
        value: ${{ jobs.testjob.outputs.b64 }}

jobs:
  testjob:
    runs-on: ubuntu-22.04
    outputs:
      b64: ${{steps.xxx.outputs.result}}
    steps:
      - env:
          VARS: ${{toJson(vars)}}
        run: |
          echo ${VARS}
      - id: xxx
        uses: actions/github-script@v7
        with:
          result-encoding: string
          # retries: 3
          script: |
            core.info(JSON.stringify(context.payload?.pull_request?.base, null, 2));
            core.exportVariable('YYYYYY', 'yyyyyyy');
            core.info(context.eventName);
            core.info(JSON.stringify(Object.keys(context.payload)));