name: matrix-callee
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      sleep:
        type: number
        required: true
      success:
        type: boolean
        required: true

jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: first-job-first-step
        env:
          name: ${{inputs.name}}
        run:
          echo $name
  second-job:
    needs: ['first-job']
    runs-on: ubuntu-22.04
    steps:
      - name: second-job-first-step
        env:
          name: ${{inputs.name}}
          success: ${{inputs.success}}
          sleep: ${{inputs.sleep}}
        run: |
          if ${{inputs.success}}; then
            echo success
          else
            echo "::error::error"
            exit 1
          fi
  third-job:
    needs: ['second-job']
    if: ${{!cancelled()}}
    runs-on: ubuntu-22.04
    steps:
      - name: check
        env:
          result: ${{needs.second-job.result}}
        run: |
          echo $result