on:
  pull_request: {}
  push: {}
  workflow_dispatch:
    inputs:
      test:
        type: choice
        required: false
        default: "-"
        options: ["a", "-"]

env:
  ENV: PROD
  test: ${{inputs.test != '-' && inputs.test || '' }}

jobs:
  my-job0:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "ref_type: $ref_type"
          echo "ref_name: $ref_name"
          echo "ref: $ref"
          echo "sha: $sha"
          echo "event_name: $event_name"
          echo "pullrequest_number: $pullrequest_number"
          echo "merge_commit_sha: $merge_commit_sha"

        env:
          ref_type: ${{github.ref_type}}
          ref_name: ${{github.ref_name}}
          ref: ${{github.ref}}
          sha: ${{ github.sha }}
          event_name: ${{ github.event_name }}
          pullrequest_number: ${{ github.event.pull_request.number }}
          merge_commit_sha: ${{ github.event.pull_request.merge_commit_sha }}
