name: my-workflow3
on:
  workflow_dispatch: 

jobs:
  my-job:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: xxx
        uses: ./.github/actions/my-action3
        # run: |
        #   echo "test=aaaaa" > $GITHUB_OUTPUT
      - name: xxx
        shell: bash
        run: |
          echo $test
        env:
          test: ${{steps.xxx.outputs.test[0]}}
      
