on:
  # pull_request: {}
  push: {}
  workflow_dispatch: {}

env:
  ENV: PROD

jobs:
  my-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: my-step
        uses: ./.github/actions/my-custom-action
