on: 
  pull_request: {}
  push: {}
  workflow_dispatch: {}

jobs:
  my-job:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          ls
          echo ${{github.event.pull_request.number}}
          echo ${{github.ref}}
          echo ${{github.sha}}
          gh api graphql -f query='{
            repository(owner: "wild-nyankoman",name: "my-inspection") {
              pullRequests(states: [OPEN], first: 100, orderBy: { field: UPDATED_AT, direction: DESC }) {
                nodes {
                  baseRefName
                  baseRefOid
                  headRefName
                  headRefOid
                  potentialMergeCommit {
                    message
                    oid
                  }
                }
              }
            }
          }'
        env:
          GH_TOKEN: ${{ github.token }}