on:
  pull_request: {}
  push: {}
  workflow_dispatch: {}

jobs:
  my-job0:
    runs-on: ubuntu-22.04
    steps:
      - id: step1
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo !!!!!!!!!
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "accept: application/vnd.github.raw+json" \
            /repos/${{ github.repository }}/contents/pnpm-lock.yaml > pnpm-lock.yaml
          echo ----------
          core_version=$(cat pnpm-lock.yaml | yq '.importers.".".dependencies.@actions/core.version')

          echo "core_version=$core_version" >> $GITHUB_OUTPUT
      - env:
          JSON: |
            {
              "dependencies": {
                "@actions/core": "${{steps.step1.outputs.core_version}}",
              }
            }
        run: |
          echo $JSON > package.json
          cat package.json
          rm pnpm-lock.yaml
          npm install
            
          

