on:
  workflow_dispatch: {}

jobs:
  my-job0:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "WORKFLOW: $WORKFLOW"
          echo "EVENT_NAME: $EVENT_NAME"
        env:
          WORKFLOW: ${{ github.workflow }}
          EVENT_NAME: ${{ github.event_name }}
  my-job1:
    uses: ./.github/workflows/my-workflow2.yml


