on:
  pull_request: {}
  push: {}
  workflow_dispatch: {}

env:
  PLAYWRIGHT_DIR: ${{github.workspace}}/pw
  PLAYWRIGHT_BROWSERS_PATH: ${{github.workspace}}/pw/bin
  PLAYWRIGHT_NPM_CACHE: ${{github.workspace}}/pw/.npmcache
  PLAYWRIGHT_VERSION: 1.48.2

jobs:
  my-job0:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/cache@v4
        with:
          key: playwright-${{env.PLAYWRIGHT_VERSION}}
          path: ${{env.PLAYWRIGHT_DIR}}
      - run: |
          npm init -y
          npm config set cache $PLAYWRIGHT_NPM_CACHE
          mkdir -p $PLAYWRIGHT_NPM_CACHE
          npx playwright@$PLAYWRIGHT_VERSION install --with-deps chromium firefox webkit

          echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
          echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
          echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
          ls $PLAYWRIGHT_NPM_CACHE
          echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
          echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
          echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
          ls $PLAYWRIGHT_BROWSERS_PATH
          echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
          echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
          echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

            
          

