name: my-workflow3
on:
  workflow_dispatch: 

jobs:
  my-job:
    runs-on: ubuntu-22.04
    outputs:
      test: ${{fromJson(steps.xxx.outputs.test)}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: xxx
        uses: ./.github/actions/my-action3
  second-job:
    needs: ["my-job"]
    strategy:
      matrix:
        test: ${{needs.my-job.outputs.test}}
    runs-on: ubuntu-22.04
    steps:
      - name: xxx
        env:
          test: ${{matrix.test.test}}
        run: |
          echo $test
        
      
