name: sugoi-workflow
on:
  workflow_dispatch: {}

jobs:
  my-job0:

    name: なんかデプロイしたい${{ github.ref }}
    environment:
      name: Production
      url: なんかURLってどう表示されんの？
    runs-on: ubuntu-24.04-arm
    env:
      TEST: ${{ secrets.TEST }}
    steps:
      - run: |
          TSET=$(echo $TEST | rev)
          echo "SECRET: $TSET"
          echo "WORKFLOW: $WORKFLOW"
          echo "WORKFLOW_REF: $WORKFLOW_REF"
          echo "ACTION: $ACTION"
          echo "ACTION_REF: $ACTION_REF"
          echo "EVENT_NAME: $EVENT_NAME"
        env:
          WORKFLOW: ${{ github.workflow }}
          WORKFLOW_REF: ${{ github.workflow_ref }}
          EVENT_NAME: ${{ github.event_name }}
          ACTION: ${{ github.action }}
          ACTION_REF: ${{ github.action_ref }}
  my-job1:
    needs: ["my-job0"]
    uses: ./.github/workflows/my-workflow2.yml


