on:
  workflow_call: 

jobs:
  my-job:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "WORKFLOW: $WORKFLOW"
          echo "EVENT_NAME: $EVENT_NAME"
        env:
          WORKFLOW: ${{ github.workflow }}
          EVENT_NAME: ${{ github.event_name }}
