on:
  pull_request: {}
  push: {}
  workflow_dispatch: {}

jobs:
  my-job0:
    runs-on: ubuntu-22.04
    steps:
      - id: step1
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo !!!!!!!!!
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "accept: application/vnd.github.raw+json" \
            /repos/${{ github.repository }}/contents/pnpm-lock.yaml > pnpm-lock.yaml
          echo ----------
          cat pnpm-lock.yaml | yq '.importers."."."fp-ts".version'
            
          

